### ISSUE TITLE
Prompt "DLL load failed" while install binary on Win10 x64

### ISSUE THREAD

**Issue by javakevin** [rk700/PyMuPDF#58] opened 2016-06-13 03:23 UTC
Hi, Guys

I'm running PyMuPDF based on Python3.5 on Win10 X64 platform, I downloaded pymupdf-1.9.4-py35-x64.zip and installed it follow instruction but following error happend. could you please help to figure out what's the problem? thanks alot!

Traceback (most recent call last):
  File "D:\Program Files (x86)\JetBrains\PyCharm 5.0.3\helpers\pydev\pydevd.py", line 2407, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "D:\Program Files (x86)\JetBrains\PyCharm 5.0.3\helpers\pydev\pydevd.py", line 1798, in run
    launch(file, globals, locals)  # execute the script
  File "D:\Program Files (x86)\JetBrains\PyCharm 5.0.3\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc) 
  File "E:/Moxtra/PyWorkspace/main/pdf_tool.py", line 3, in <module>
    import fitz
  File "D:\Python\Python35\lib\site-packages\fitz\__init__.py", line 2, in <module>
    from fitz.fitz import *
  File "D:\Python\Python35\lib\site-packages\fitz\fitz.py", line 18, in <module>
    _fitz = swig_import_helper()
  File "D:\Python\Python35\lib\site-packages\fitz\fitz.py", line 17, in swig_import_helper
    return importlib.import_module(mname)
  File "D:\Python\Python35\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: DLL load failed:

All the best,
-Kevin Wu

**Comment by javakevin** [comment] 2016-06-13 07:20
tried on Win8 with Python2.7, the same issue still.

**Comment by JorjMcKie** [comment] 2016-06-13 08:59
Hi @javakevin - so far I have no clue what is happening on your machine. I tried to re-create your error. I downloaded the zip file, re-installed fitz with it and did a basic test. Protocol is further down. Any chance to find out which DLL could not be loaded? Can you confirm that all 4 fitz installation files have landed in the correct directory of your installation? These are ``__init__.py``, ``fitz.py``, ``_fitz.pyd``, ``utils.py``. The installation script ``setup.py`` relies on a standard Python directory configuration and uses the directory name it gets from ``distutils.sysconfig.get_python_lib``. All I can image is that something is going wrong here.
Can you try to manually copy these 4 files to where they should be in your Python?
If it works then, the problem is in the setup script (I am ready to bet on it: I have seen D: and E: drives flying around in your protocol ...).


```
C:\Users\Jorj\Desktop\fitz>py setup.py install
running install
running build
running build_py
running install_lib
creating C:\Users\Jorj\AppData\Local\Programs\Python\Python35\Lib\site-packages\fitz
copying build\lib\fitz\fitz.py -> C:\Users\Jorj\AppData\Local\Programs\Python\Python35\Lib\site-packages\fitz
copying build\lib\fitz\utils.py -> C:\Users\Jorj\AppData\Local\Programs\Python\Python35\Lib\site-packages\fitz
copying build\lib\fitz\__init__.py -> C:\Users\Jorj\AppData\Local\Programs\Python\Python35\Lib\site-packages\fitz
byte-compiling C:\Users\Jorj\AppData\Local\Programs\Python\Python35\Lib\site-packages\fitz\fitz.py to fitz.cpython-35.pyc
byte-compiling C:\Users\Jorj\AppData\Local\Programs\Python\Python35\Lib\site-packages\fitz\utils.py to utils.cpython-35.pyc
byte-compiling C:\Users\Jorj\AppData\Local\Programs\Python\Python35\Lib\site-packages\fitz\__init__.py to __init__.cpython-35.pyc
running install_data
copying fitz\_fitz.pyd -> C:\Users\Jorj\AppData\Local\Programs\Python\Python35\Lib\site-packages\fitz
running install_egg_info
Writing C:\Users\Jorj\AppData\Local\Programs\Python\Python35\Lib\site-packages\fitz-1.9.1-py3.5.egg-info
C:\Users\Jorj\Desktop\fitz>cd..
C:\Users\Jorj\Desktop>py -3.5
Python 3.5.1 (v3.5.1:37a07cee5969, Dec  6 2015, 01:54:25) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import fitz
>>> print(fitz.__doc__)
PyMuPDF 1.9.1: the Python bindings for the MuPDF 1.9a library,
created on 2016-06-06 07:28:09
>>>
>>> pix = fitz.Pixmap("test.png")
>>> dir(pix)
['__class__', '__del__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattr__',
'__getattribute__', '__gt__', '__hash__', '__init__', '__le__', '__len__', '__lt__', '__module__', '__ne__', '__new__',
'__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__swig_destroy__',
'__swig_getmethods__', '__swig_setmethods__', '__weakref__', '_getSamples', '_writeIMG', 'clearWith', 'copyPixmap',
'gammaWith', 'getColorspace', 'getIRect', 'getPNGData', 'getSize', 'h', 'height', 'interpolate', 'invertIRect', 'n',
'samples', 'samplesAlpha', 'samplesRGB', 'this', 'tintWith', 'w', 'width', 'writeImage', 'writePNG', 'x', 'xres', 'y',
'yres']
>>> repr(pix)
'fitz.Pixmap(fitz.csRGB, fitz.IRect(0, 0, 949, 620))'
>>>
```

**Comment by javakevin** [comment] 2016-06-13 09:23
@JorjMcKie thanks for your replay! 
My python home is D:\Python\Python35\
It seems all the 4 files are installed in `%PYTHON_HOME%\Lib\site-packages` successfully.
![snapshot1](https://cloud.githubusercontent.com/assets/1628444/16002549/dd386c16-318a-11e6-9c8b-ec151d91e8a5.png)

I printed `distutils.sysconfig.get_python_lib` and it shows `D:\Python\Python35\Lib\site-packages`, i assume it is the correct position.

After that, i re-install the zip and compare the logs with yours, seems no difference
`C:\pymupdf-1.9.4-py35-x64\fitz>py setup.py install
running install
running build
running build_py
running install_lib
creating D:\Python\Python35\Lib\site-packages\fitz
copying build\lib\fitz\fitz.py -> D:\Python\Python35\Lib\site-packages\fitz
copying build\lib\fitz\utils.py -> D:\Python\Python35\Lib\site-packages\fitz
copying build\lib\fitz\__init__.py -> D:\Python\Python35\Lib\site-packages\fitz
byte-compiling D:\Python\Python35\Lib\site-packages\fitz\fitz.py to fitz.cpython-35.pyc
byte-compiling D:\Python\Python35\Lib\site-packages\fitz\utils.py to utils.cpython-35.pyc
byte-compiling D:\Python\Python35\Lib\site-packages\fitz\__init__.py to __init__.cpython-35.pyc
running install_data
copying fitz\_fitz.pyd -> D:\Python\Python35\Lib\site-packages\fitz
running install_egg_info
Removing D:\Python\Python35\Lib\site-packages\fitz-1.9.1-py3.5.egg-info
Writing D:\Python\Python35\Lib\site-packages\fitz-1.9.1-py3.5.egg-info`


It's verify strange, did i missed any steps? 
thanks again. @JorjMcKie

**Comment by JorjMcKie** [comment] 2016-06-13 09:45
Hm, strange indeed!
If you start the Python interpreter like I did it in my test, the problem is the same?
Other packages you installed after Python installation work with no problem?

The ``_fitz.pyd`` binary is UPX-compressed. As a last resort, you could de-compress it and retry. Hope you have UPX on your machine. The uncompress command is ``upx.exe -d _fitz.pyd``. This will increase the file size to 9421 KB.

**Comment by javakevin** [comment] 2016-06-13 09:58
I just did exactly as what you did.. the bad news is upx report "not packed by upx " error when i decompress it..
![snapshot2](https://cloud.githubusercontent.com/assets/1628444/16003653/51666228-3190-11e6-977a-ae174c0f7b76.png)

**Comment by JorjMcKie** [comment] 2016-06-13 10:17
Ahh - now we have at least something in our hands. Maybe something went wrong with your download.

I will upload a fitz setup version where the binary is **not** packed. Just give me some time for this. I will notity you, when you can download it again, ok?

**Comment by javakevin** [comment] 2016-06-13 10:23
Sure! thanks very much @JorjMcKie

**Comment by JorjMcKie** [comment] 2016-06-13 10:35
Done. Please download file ``pymupdf-1.9.5-py35-x64.zip`` (only this one). I have just decided to drop the UPX compression alltogether, so the other files will follow shortly.
Good luck!

**Comment by JorjMcKie** [comment] 2016-06-13 10:41
One more comment: your directory printout of fitz showed a PYD file size of around 4 MB. That **just has** to be a packed version! The unpacked original is around 9 MB. If now your UPX says the PYD is not compressed by UPX, then the file must contain erroneous data, no doubt.

**Comment by rk700** [comment] 2016-06-13 13:03
Maybe we can use MD5 or some kind of hash for integrity verification.

**Comment by JorjMcKie** [comment] 2016-06-13 13:07
@rk700 exactly - I am testing this already ...

**Comment by javakevin** [comment] 2016-06-14 02:08
still not work.. is this pyd file depends on any system dlls which i don't have? 

![depends](https://cloud.githubusercontent.com/assets/1628444/16029018/e759321a-3217-11e6-94a6-70bae3d412f9.png)
![structure](https://cloud.githubusercontent.com/assets/1628444/16029020/ec0cae9a-3217-11e6-9847-4d71ef4a4084.png)

**Comment by JorjMcKie** [comment] 2016-06-14 10:33
How bad! I am a little out of good advice now. When you do the ``import fitz``, do you still get the same exception?
I can also not see from your diagnostics just which components are missing. I had a look at ``_fitz.pyd`` on my Python 3.5 with dependency walker as you did: I am getting exactly the same results as you do, so this is not the problem.

Depending on how urgent your interest in PyMuPDF is, you could try and fall back to generating the binary yourself - see the respective Wiki.

I will not give up however. If there is anything that prevents using my binaries on certain systems, I certainly want to know what that is.
What type of computer and Windows version are you running: I am using this Windows 10 Pro version:
```
Microsoft Windows [Version 10.0.10240]
(c) 2015 Microsoft Corporation. Alle Rechte vorbehalten.
C:\>
```
Running on a desktop with AMD FX Eight-Core processors at 4,00 GHz.
Next I will try to reproduce everything on my wife's Laptop with Windows 10 Home.

**Comment by JorjMcKie** [comment] 2016-06-14 11:36
A first result:
Installed Win10 Home in a virtual machine and got your problem!
Will further investigate now.
```
Python 3.5.1 (v3.5.1:37a07cee5969, Dec  6 2015, 01:54:25) [MSC v.1900 64 bit (AMD64)] on win32
Type "copyright", "credits" or "license()" for more information.
>>> import fitz
Traceback (most recent call last):
  File "<pyshell#0>", line 1, in <module>
    import fitz
  File "C:\Users\Jorj\AppData\Local\Programs\Python\Python35\lib\site-packages\fitz\__init__.py", line 2, in <module>
    from fitz.fitz import *
  File "C:\Users\Jorj\AppData\Local\Programs\Python\Python35\lib\site-packages\fitz\fitz.py", line 18, in <module>
    _fitz = swig_import_helper()
  File "C:\Users\Jorj\AppData\Local\Programs\Python\Python35\lib\site-packages\fitz\fitz.py", line 17, in swig_import_helper
    return importlib.import_module(mname)
  File "C:\Users\Jorj\AppData\Local\Programs\Python\Python35\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: DLL load failed: Das angegebene Modul wurde nicht gefunden.
>>> 

```

**Comment by JorjMcKie** [comment] 2016-06-14 11:54
I think I got it!!
Again I will upload a new version for Py3.5-x64 and send you a note. @javakevin - please do test it as soon as you can to make sure it solves your problem.
Thanks

**Comment by JorjMcKie** [comment] 2016-06-14 12:23
@javakevin you can now retry.
The corrected binary version uploaded was generated with a modified set of linker options. To my surprise, the Home and Pro versions of Windows do differ in terms of common runtime libraries. The new linker options make sure these routines are bound to ``_fitz.pyd``.
On my Win10 Home machine PyMuPDF works with Python 3.5 64bit. I can work with documents and graphics.
So you I hope you are set using it ...

**Comment by javakevin** [comment] 2016-06-15 01:52
It works finally with the latest build!!  @JorjMcKie  as you mentioned, my OS is Win10 Pro which directly upgraded from Win7. Thanks for your professional help and quick answer! :+1: 
I can't wait to start the PyMuPDF journey now..

**Comment by JorjMcKie** [comment] 2016-06-15 02:00
Thank you and welcome to the PyMuPDF "community" :-)
Please do not hesitate to ask for help or advice in the future.

**Closed** 2016-06-15 06:54 UTC
