### ISSUE TITLE
What is the best way to build a custom getText format

### ISSUE THREAD

**Issue by juviwhale** [rk700/PyMuPDF#111] opened 2017-12-20 01:20 UTC
Our application requires a specific format for the text layout of a given page. We need a format that is basically a JSON object that has a nesting:, 

```
<page> (width and height)
    <block> (its rectangle)
        <line> (its rectangle)
            <word> (its rectangle, (x, y) coordinates and value)
``` 

Unfortunately since the JSON format does not provide a distinction for the positions of the words that is a no go (and v1.12 doesn't help either). I know I could try to get this done by using the XML format and using a XML module, however I would have to implement some **layout analysis** to merge the characters => words correctly and mostly I concerned that I may be adding be adding unnecessary overhead of producing and then parsing the entire xml output. 

Is there a different approach I am missing?

*Note:* Regarding the layout analysis of the XML format, I have been assuming that the space between words in a span would not always be represented by a space character element. Is this a bad assumption?

e.g. 

```
<char bbox="51.685753 79.300354 53.90575 93.04035" x="51.685753" y="90.050354" c="H"/>
<char bbox="53.90575 79.300354 58.90575 93.04035" x="53.90575" y="90.050354" c="i"/>
<char bbox="58.90575 79.300354 61.685753 93.04035" x="58.90575" y="90.050354" c=" "/>
<char bbox="61.685753 79.300354 64.46575 93.04035" x="61.685753" y="90.050354" c="t"/>
<char bbox="64.46575 79.300354 70.02576 93.04035" x="64.46575" y="90.050354" c="t"/>
<char bbox="70.02576 79.300354 72.805756 93.04035" x="70.02576" y="90.050354" c="h"/>
<char bbox="72.805756 79.300354 78.36575 93.04035" x="72.805756" y="90.050354" c="e"/>
<char bbox="78.36575 79.300354 81.695755 93.04035" x="78.36575" y="90.050354" c="r"/>
<char bbox="81.695755 79.300354 83.91576 93.04035" x="81.695755" y="90.050354" c="e"/>
```

**Comment by JorjMcKie** [comment] 2017-12-20 11:17
Your analysis is quite right - in all its aspects.

JSON v1.12 is even a little worse in terms of position info compared to v1.11, because the new JSON spans now do not have rectangles either - only lines have. From my personal requirements I am exactly looking at resolving this, too.

As a first step in that direction, I have written a method, that returnes text **blocks** (with their rectangles) of a page - very fast because it is in C. It is named `Page.getTextBlocks()` and directly returnes a Python list of these blocks, each entry is the list `[x0, y0, x1, y1, text]`, where "text" consists of the concatenated lines of the block.

As a second step, I wrote a Python script that returns all **words** with their rectangles. This one is based on the XML output:

```
import fitz
from lxml import etree
from operator import itemgetter

# =============================================================================
# WordList
# =============================================================================
def WordList(xml):
    root = etree.fromstring(xml)
    word_list = []
    for block in root.findall("block"):
        for line in block.findall("line"):
            line_d = dict(line.items())
            bbox = line_d["bbox"].split(" ")
            r = fitz.Rect(float(bbox[0]), float(bbox[1]),
                          float(bbox[2]), float(bbox[3]))
            x0, y0, x1, y1 = list(r)       # line rectangle coordinates
            for font in line.findall("font"):    # this loop glues together words from characters
                word = ""
                for ch in font.findall("char"):
                    char_d = dict(ch.items())
                    c = char_d["c"]
                    bbox = char_d["bbox"].split(" ")    # rectangle of character
                    r = fitz.Rect(float(bbox[0]), float(bbox[1]),
                                  float(bbox[2]), float(bbox[3]))
                    if c != " ":         # append non-space chars to word
                        word += c
                        x1 = r.x1    # update end-of-word coordinate
                        continue
                    word_list.append([x0, y0, x1, y1, word])  # output word when space encountered
                    word = ""    # reset word string
                    x0 = r.x1   # the new start-of-word coordinate
                if word != "":
                    word_list.append([x0, y0, x1, y1, word])
    # this sorts the words using (y0, x0) as sort key. Could be changed / omitted
    word_list.sort(key = itemgetter(1, 0))
    return word_list

# =============================================================================
# Main
# =============================================================================
if __name__ == "__main__":
    doc = fitz.open(filename)
    xml = doc[n].getText("xml")
    word_list = WordList(xml)
    # each entry is `[x0, y0, x1, y1, word]`.
```
This is based on the v1.12 XML output, but can be easily adapted to v1.11.

You are right here, too: neighboring words in a line (having same y0) need not be separated by space(s), e.g. when members of different columns of a table-like text.

As you say, we have that XML overhead. As a performance freak, I find it disturbing to produce a very fine-grain information in the first place (and producing this in the memory-consuming XML format on top) and then secondly, forget most of it again  - using yet another package (the highly efficient **lxml** in this case).

What I am considering is creating the above word list directly - again written in C. This would have obvious advantages and shouldn't be much harder to do than my getTextBlocks above.

I would appreciate your input: would that address your requirement?

**Comment by juviwhale** [comment] 2017-12-20 23:16
Yeah it does. Thanks for the example. As you point out there are obvious customization benefits to processing the XML. 

Our format requirement here is a little different, a bit more nested, because we are trying to produce a format that closely matches/replaces the  
[Microsoft's Computer Vision OCR API](https://westus.dev.cognitive.microsoft.com/docs/services/56f91f2d778daf23d8ec6739/operations/56f91f2e778daf14a499e1fc) format. That format is roughly: 

```
{
  "regions": [
    {
      "boundingBox": "462,379,497,258",
      "lines": [
        {
          "boundingBox": "462,379,497,74",
          "words": [
            {
              "boundingBox": "462,379,41,73",
              "text": "A"
            },
            {
              "boundingBox": "523,379,153,73",
              "text": "GOAL"
            },
            .....
          ]
        },
        .....
      ]
    },
    .....
  ]
}
```

*NOTE: yeah I know..their `boundingBox` values as strings are silly, we reformat those*

Now with my base req above stated, it would be nice to perhaps retain some font information just as an aid for deciphering the connected/unconnected text spans. (E.g form field headers - **Name** *Tom*). Relying on the text box height to assume font size has not been reliable enough. 

The *one concern* I have with the approach you outlined is the rare **terribly formatted PDF** we come upon where all the text blocks consist of single characters or word fragments. We have been relying on pdfminer to deal with the layout analysis for us. I fear reimplementing such layout analysis after the XML generation may lose some of the gains over pdfminer in performance but maybe it is not a big hit.

e.g.
![eg](https://user-images.githubusercontent.com/6657003/34232936-99f73d0c-e597-11e7-9e1d-07468c736de8.png)

I have a few other questions but they are unrelated enough that they would be best in a different ticket.

Thanks for all the hard work given to this package.

**Comment by JorjMcKie** [comment] 2017-12-21 00:25
I am not sure I completely understand. Let me state a few (bold) thesis:
1. As far as **performance** is concerned, pdfminer is no competition to PyMuPDF XML output. If you look at the performance chapter of our docu, you'll see why. There actually are few packages on the market (freeware or not) who can compete with the speed of MuPDF. That's also true for Xpdf / Poppler.
2. I believe you will find all information you require in the XML output. You do have font information, font size, and the rectangle where each single character sits in. I always thought the problem is how to **forget** such tremendous detail.

What you seem to hint at is: when can I assume a character to be part of a specific word, e.g. when its rectangle height / vertical position differes only a little from its djacent colleagues? Right? And, similarly, what is the tolerable distance to regard a character as being a member of a word.

If the previous is true, I think you cannot find better information than given in XML output.

Let me sketch a few things to underpin this.
You can find out the character width of a given character when displayed with a certain font and font size with PuMuPDF. If the character's distance to a string is smaller than the width of `chr(32)`  (= space char) you could assume, that it is part of the adjacent word.

The function I displayed above should already do that (with the help of MuPDF). Instead of using float coordinates as I did there, you could use IRects (rectangles rounded to pixels). This should force characters to be on the same integer line height which previously only where approximately equal in float coordinates. Similar applies to character spacing.

Your above "quick bown fox" example can be handled by the sketched approach: either something **is** a space, or not. If not and if its charatcer representation has been recognized as "" then it can be completely ignored as buzz (potentially subject to its width also being `< width(chr(32))`).

**Comment by JorjMcKie** [comment] 2017-12-21 12:54
I have written a C routine that creates that said word list without needing the XML detour. I.e. each word together with its bbox is an entry of a Python list directly returned by the new method.
I am still confirming the correctness of all the numbers, but the performance gain is already clear: it is **HUGE!**

Scanning through our docu PDF with its 150 pages, and the Adobe manual with its 1.310 (!) pages showed the following results (in seconds, **XML read** is done by `PyMuPDF`, **XML processing** done by `lxml`):

**PyMuPDF manual (150 pages)**
* XML read 0.4575
* XML processing 5.6718
* new word list 0.0193

**Adobe manual (1.310 pages)**
* XML read 4.1131
* XML processing 51.2651
* new word list 0.1685

In essence, the new word list creation is 24 times faster than creating the XML text of a page. It only needs about 1.3E-4 seconds per page! Processing the XML needs 12 times more time than creating it.

Taking it all together, you could get your word list **almost 300 times faster** than with the XML method.

**Comment by JorjMcKie** [comment] 2017-12-21 21:36
I have uploaded that new method a couple of hour ago in the pre-release branch v1.12.0. It is called `Page.getTextWords`.

**Comment by juviwhale** [comment] 2017-12-22 00:27
I don't want to ask you to hurt that awesome performance gain but would it be possible retain idx or generic id values of the sourced `block` and `line`. 

 ```
# each entry is `[x0, y0, x1, y1, word, block_id, line_id]`.
```

I would like to use this method but still have the ability of filtering based on block/line or rebuilding a nested format.

**Comment by JorjMcKie** [comment] 2017-12-22 00:58
What I could easily do is just tracking the block and line numbers, and maybe even the word number and putting those 3 counters behind the word's text as you indicated:c `[x0, y0, x1, y1, word, block_no, line_no, word_no]`.
Am I getting you right?
That shouldn't impact the performance.

**Comment by JorjMcKie** [comment] 2017-12-22 01:55
Wasn't difficult. We are still 300 times faster, though somewhat slowed down (maybe 10% or so).

**Closed** 2018-01-06 15:15 UTC
Labels: question
