### ISSUE TITLE
Memory leak in page.getPixmap()

### ISSUE THREAD

**Issue by thefloe1** [rk700/PyMuPDF#130] opened 2018-01-29 09:05 UTC
I'm using pymupdf to loop though all pages in a PDF and extracting pages from it:
```
doc = fitz.open(filename)
for num,page in enumerate(doc):
	pix = page.getPixmap(m)
	data = pix.getPNGData()	
	# doing some magic here
```
Using memory profiler I see that every loop getPixmap allocates 20MB of data which are not freed. I tried different things like `del pix` or `gc.collect` but the memory usage increases every run. As I'm handling quiet some pages, my scripts runs out of memory...

getPixmap also shops the following warning/error:
```
error: Unable to read ICC workflow
warning: Attempt to read Output Intent failed
```

**Comment by JorjMcKie** [comment] 2018-01-29 14:13
I am on a journey abroad, so I am limited to dig into this very much. I'll be back Thirsday next week.

Anyway, this sounds like a problem that I thought was fixed. Please provide me with your system parameters: OS, bitness, Python version and PyMuPDF version.
I will at least be able to look into the source.

Are you sure that the memory accumulation is caused by pixmap creation - and not by the getPNGdata method?

**Comment by thefloe1** [comment] 2018-01-29 14:43
Hi,
It's definitely on the getPixmap. 

OS is Win 10, 64bit, 
Phyton 2.7.12 (32bit), 
PyMuPDF 1.12.2: Python bindings for the MuPDF 1.12.0 library

I see the same memory behavior when running the demo pdf viewer (PDFdisplay.py).

**Comment by JorjMcKie** [comment] 2018-01-29 18:55
ok, thanks for the info. That's pixmap creation then.
As I said, give me some time / opportunity to look into that ...

**Comment by JorjMcKie** [comment] 2018-02-04 08:32
I have found the cause for the issue, and I am testing the fix.
I will upload it next week, probably Thursday.

**Comment by thefloe1** [comment] 2018-02-04 08:34
Thanks a lot

**Comment by JorjMcKie** [comment] 2018-02-09 00:45
Just uploaded a fix into branch 1.12.2.
Please check that your issue is being resolved.

**Comment by JorjMcKie** [comment] 2018-02-12 10:42
What is your OS and PyMuPDF version time stamp?
I am on Win 10 x64 and used the following session (Python 3.6.4 x64).
* I created pixmaps for all 1310 pages of the Adobe manual.
* after open I had 40 MB memory usage:
![start](https://user-images.githubusercontent.com/8290722/36092711-b1e3559e-0fbe-11e8-8ed1-d4a126dc3102.PNG)
* at the end, this had increased to 94 MB:
![stop-1](https://user-images.githubusercontent.com/8290722/36092770-dc196cb8-0fbe-11e8-9c4d-4aea1fb6b728.png)
* deleting the leftover page and pixmap objects from the loop, this dropped to 92.5 MB:
![stop-2](https://user-images.githubusercontent.com/8290722/36092820-16a6f396-0fbf-11e8-8ef9-c6696edc39bc.png)
* after closing the document, memory usage went down to 26.4 MB (below my start value 40 MB after open):
![stop-3](https://user-images.githubusercontent.com/8290722/36092903-5fb1b42c-0fbf-11e8-998d-6930d0465125.png)

So from my end, I find your 400 MB confusing. I will now go ahead and also create PNG images from each pixmap to see what that impact is ...

**Comment by JorjMcKie** [comment] 2018-02-12 10:54
Hmm, no big change either:
* I am going up to 97 MB now
![stop-1](https://user-images.githubusercontent.com/8290722/36093594-83061f24-0fc1-11e8-8e86-2797aa9c6fe5.png)

**Comment by JorjMcKie** [comment] 2018-02-12 10:56
Maybe I should be using an example with larger pages than this one? Let me try more documents ...

**Comment by JorjMcKie** [comment] 2018-02-12 11:04
With larger page sizes (100 A4 pages, complex graphics) I am also staying around 100 MB.
It still is hard to explain, why I should have an increase at all after the first pixmap ...

**Comment by JorjMcKie** [comment] 2018-02-12 13:49
I did some MuPDF store memory analysis: Obviously, their strategy is to maintain stuff in memory as much as possible for performance reasons
For example, any font or image once encountered is held in memory. There do exist low-level functions to exert some control, too.
Like deleting some store memory by percentage value and so on.

**Comment by JorjMcKie** [comment] 2018-02-12 20:37
To complete my investigation, I rendered the file mentioned above (100 A4 pages, complex graphics ...) with MuPDF's `mutool draw` utility:
The memory usage behavior was exactly equal to that of my interactive session I sent you previously (slowly increasing to a 97 MB peak usage, ...).

The mentioned utility has an additional feature: one can empty the storable memory cache after each page has been processed. This keeps memory usage low (below 20 MB in this case) - of course at the cost of processing speed (first measurements point to 60% longer runtime).

**Comment by JorjMcKie** [comment] 2018-02-13 12:36
Since yesterday I've been trying a few things to make sure that we no longer have a memory leak in PyMuPDF.
To this end, I implemented a new class `Tools` for testing purposes (not uploaded to the repo). It has methods `store_size()` and `empty_store()` among others.
I then used the following 2 scripts for a number of PDFs:
```
import time, fitz, sys
fname = sys.argv[1]
doc = fitz.open(fname)

t0 = time.clock()
for page in doc:
    pix = page.getPixmap()

t1 = time.clock()
print("time without storage reset %g" % (t1-t0))
```

```
import time, fitz, sys
fname = sys.argv[1]
doc = fitz.open(fname)
tools = fitz.Tools()

t0 = time.clock()
for page in doc:
    tools.empty_store()
    pix = page.getPixmap()
    
t1 = time.clock()
print("time with storage reset %g" % (t1-t0))
```

The second script empties the store before each new pixmap. This keeps memory usage down to the minimum required by the opened document itself, let's say in the ballpark of 10 MB. After closing / deleting the document, memory usage dropped again close to the start value.

The second script needed a considerably increases runtime: my science magazine (the 100 pager) needed 20% longer, and the Adobe manual more than 100%.
Certainly, method `Tools.store_size()` (very fast - just a check of a field) could be used to only empty the store, when it exceeds a threshold - thus decreasing the runtime impact.

I would however argue, that there already **exists** such a threshold: the aforementioned 256 MB built into PyMuPDF. If you wanted, you could change that value in file `fitz_wrap.c` in statement `gctx = fz_new_context(NULL, NULL, FZ_STORE_DEFAULT);` (close to the end of the file) and replace `FZ_STORE_DEFAULT` with a value of your liking.

Please let me know your reaction.

**Closed** 2018-02-21 17:08 UTC

**Comment by JorjMcKie** [comment] 2018-12-21 15:50
Hi,
this is a fairly long comment chain ... so I don't know what exactly you are referring to.
Just did a page.getText() for all 1310 pages of the Adobe manual without complaints ...
Best you send me the script and data to reconstruct your case.

**Comment by JorjMcKie** [comment] 2018-12-21 15:53
if you mean the icc related messages, you can just ignore them.
If you upgrade to v1.14, those messages will also be suppressed.

If you however are getting memory leaks (the actual topic of this issue!), then I am indeed alarmed.

**Comment by wave-DmP** [comment] 2018-12-21 15:59
I've tested the script and i'm getting the ICC warning for each page that getText() is called on. I annotate each page subsequently and that doesn't give any warnings.  The warnings don't appear for a 2 page document though.  Sending data is no possible unfortunately.

Since there is no reduction in performance or function, I suspect it may be just the warnings.
Is it possible to manually suppress the ICC warnings from the script?

**Comment by JorjMcKie** [comment] 2018-12-21 16:09
Yes, these are warnings.
Please upgrade to PyMuPDF v1.14.x  -- this version captures messages like these, coming from the underlying C-library MuPDF.

I was a bit frightened at first, but I now understand you picked the wrong issue - your observation has nothing to do with memory leaks obviously ...

**Comment by wave-DmP** [comment] 2018-12-21 16:11
fair enough, it was the first and only search result for the warning text and pymupdf :)

I'll upgrade and see if the issue is solved, thx!

**Comment by buptyyf** [comment] 2022-12-05 02:58
> What is your OS and PyMuPDF version time stamp? I am on Win 10 x64 and used the following session (Python 3.6.4 x64).
> 
> * I created pixmaps for all 1310 pages of the Adobe manual.
> * after open I had 40 MB memory usage:
>   ![start](https://user-images.githubusercontent.com/8290722/36092711-b1e3559e-0fbe-11e8-8ed1-d4a126dc3102.PNG)
> * at the end, this had increased to 94 MB:
>   ![stop-1](https://user-images.githubusercontent.com/8290722/36092770-dc196cb8-0fbe-11e8-9c4d-4aea1fb6b728.png)
> * deleting the leftover page and pixmap objects from the loop, this dropped to 92.5 MB:
>   ![stop-2](https://user-images.githubusercontent.com/8290722/36092820-16a6f396-0fbf-11e8-8ef9-c6696edc39bc.png)
> * after closing the document, memory usage went down to 26.4 MB (below my start value 40 MB after open):
>   ![stop-3](https://user-images.githubusercontent.com/8290722/36092903-5fb1b42c-0fbf-11e8-998d-6930d0465125.png)
> 
> So from my end, I find your 400 MB confusing. I will now go ahead and also create PNG images from each pixmap to see what that impact is ...

I must call doc.close() at the end of use pdf doc? I see memory not recycle after I use fitz.open().
