### ISSUE TITLE
Document embeddedFileCount Not Recognizing Embedded Attached

### ISSUE THREAD

**Issue by refayathaque** [rk700/PyMuPDF#182] opened 2018-06-27 13:36 UTC
`count = doc.embeddedFileCount` is returning 0 when in reality there is an embedded attachment, which is a csv. Does PyMuPDF not recognize csv files as attachments to PDFs?

Furthermore, how would I go about extracting an attachment from a PDF into my system directory?

Thank you so much.

**Comment by JorjMcKie** [comment] 2018-06-27 15:29
Hm - impossible to tell without more info. Pls send me the PDF.

You sure it is an `/EmbeddedFiles`  file?
And not a file attachment **annotation**? Those are different things ...  Annotations are always bound to a specific page, embedded files "belong" to the document, not a page.

Either case is supported by PyMuPDF, and there is no restriction to supported file types:
You can change relevant metainformation, extract and update / replace the file content. See the documentation. In short:

- **FileAttachment annotations:** `Annot.fileInfo()` (metadata), `Annot.fileGet()` (file content as a `bytes` object, `Annot.fileUpd()` replace the file content and metadata. I currently do not support **new** `FileAttachment` annotations.

- **Embedded files:** you can etract the file (your question I think) via `Document. embeddedFileGet(n)`, a `bytes` object, where `n` is either the name under which the file has been embedded, or the number (0-based). If you are not sure what to take, browse through the embed and print the name, or the complete metadata of each. For this type of embedding, the full range of functions is available: add, delete, update, information.

**Comment by JorjMcKie** [comment] 2018-06-27 15:44
Some more remarks. Your wording is ambiguous - assuming you do have a file attachment annotation, which you want to extract - do this:
1. find the page on the attched file symbols appears
2. create the resp. annotation object: first `annot = page.firstAnnot`, then while `annot.type` is not a file attachment or it is not **your** attachment, do `annot = annot.next`. Then do `s = annot.fileGet()`. Then proceed like with any file content, e.g. `fout = open("xyz.csv", "wb"); fout.write(s); fout.close()`. Note the open parameter "wb", because s is a `bytes` object.

**Comment by refayathaque** [comment] 2018-06-28 13:45
Hi @JorjMcKie ! Thanks so much for getting back to me on this, I really appreciate it. The CSV in question is most definitely NOT a File Attachment Annotation, it is purely an Embedded Attachment. How may I get in touch with you so I can send you the PDF?

**Comment by JorjMcKie** [comment] 2018-06-28 13:56
@refayathaque - please just use my e-mail, no problem: jorj.x.mckie@outlook.de

**Comment by JorjMcKie** [comment] 2018-06-28 13:58
For some reason I got your comment via GitHub's e-mail notification, but I don't see it in this blog ...

**Comment by JorjMcKie** [comment] 2018-06-28 13:59
Hi Refayat,
replying by my e-mail, because I do not se this comment showing up in GitHub for whatever reason.
Please just use this e-mail for sending the PDF.
I am eager to see what is happening …
Jorj

Gesendet von Mail<https://go.microsoft.com/fwlink/?LinkId=550986> für Windows 10

________________________________
Von: Refayat Haque <notifications@github.com>
Gesendet: Thursday, June 28, 2018 9:45:56 AM
An: rk700/PyMuPDF
Cc: Jorj X. McKie; Mention
Betreff: Re: [rk700/PyMuPDF] Document embeddedFileCount Not Recognizing Embedded Attached (#182)


Hi @JorjMcKie<https://github.com/JorjMcKie> ! Thanks so much for getting back to me on this, I really appreciate it. The CSV in question is most definitely NOT a File Attachment Annotation, it is purely an Embedded Attachment. How may I get in touch with you so I can send you the PDF?

**Comment by JorjMcKie** [comment] 2018-06-28 14:30
got it, reply underway to your gmail

**Comment by JorjMcKie** [comment] 2018-07-01 14:36
I forgot to ask:
Do any of the usual PDF viewers (e.g. Adobe Acrobat) see your embedded file?

**Comment by JorjMcKie** [comment] 2018-07-02 14:32
I am glad you found a way to get what you wanted.
I am still very interested to learn what was the cause of the zero result using (Py-) MuPDF. It would be frustrating to close this issue without some kind of solution.
Any chance to show the `/Catalog` object?
Or tell me what a standard reader like Adobe's Acrobat has to say about the attached file?

**Comment by JorjMcKie** [comment] 2018-07-05 08:00
Hi @refayathaque - I **need** to look at that PDF's structure!
Can't you encrypt it? That hides the confidential contents but leaves the structure visible.

**Comment by JorjMcKie** [comment] 2018-07-07 13:58
Hi @refayathaque  - sorry, this issue is now open for 10 days and cannot go anywhere as there is no way to investigate it.
If you find a way to prepare some of the suggested data, you are more than welcome to re-open.

**Closed by JorjMcKie** 2018-07-07 13:58 UTC
Labels: wontfix
