### ISSUE TITLE
Cannot make version 1.9 work with Gtk, wx

### ISSUE THREAD

**Issue by mozbugbox** [rk700/PyMuPDF#52] opened 2016-05-20 08:57 UTC
I don't know what was the problem, but when I have pymupdf git master HEAD compile against mupdf 1.9a, it won't work well with Gtk or wx. 

When I run the `demo/PDF_display`, the file chooser dialog pops up with most of the widgets drawn in half way.

.....
![pdf_display_pymupdf-1 9](https://cloud.githubusercontent.com/assets/1501849/15422526/9aadbcee-1eab-11e6-99a9-a988ee5b639e.jpg)

After a few test, it seems simply `import fitz` *after* `import wx` make the problem goes away.

Actually, I had the opposite experience with pymupdf version 1.8 and Gtk. With pymupdf 1.8, some segfault problems went away when `import fitz` went before `from gi.repository import Gtk`. :(

**Comment by mozbugbox** [comment] 2016-05-20 11:15
The following code segfault. Put `import fitz` in front stop crash. But fitz import first cause Gtk draw fails.

```py
import sys
from gi.repository import Gtk
import fitz
fname = sys.argv[1]
pdf = fitz.open(fname)
print(pdf.pageCount)
page = pdf.loadPage(0)
pixmap = page.getPixmap(matrix=fitz.Identity)
print(len(pixmap.samples))
```

The following will have Gtk malfunc by simply import fitz first

```py
import fitz
import sys
from gi.repository import Gtk
dlg = Gtk.Dialog("Title", None, 0, (Gtk.STOCK_OK, 1))
dlg.resize(200, 200)
dlg.connect("response", lambda *x: Gtk.main_quit())
dlg.show_all()
Gtk.main()
```

**Comment by mozbugbox** [comment] 2016-06-02 15:38
If I remove the `freetype` from linux `libraries` parameter, in the file setup.py, the problem is gone.

Why `freetype` is needed in this case? It's not exposed in the binding.

And since `'jbig2dec', 'openjp2', 'jpeg',` are included in `mupdfthird` now, those libs should not be necessary anymore.

**Comment by JorjMcKie** [comment] 2016-06-02 18:08
Oops - interesting!
Thanks for clarifying this. As I have no expertise on Linux, I couldn't have helped anyway.
Would you care closing the issue when the solution is confirmed?
We will update the setup.py accordingly then.

**Comment by mozbugbox** [comment] 2016-06-03 00:04
Actually, with further test, it seems that if I put `freetype` in front of `mupdfthird`,  the problem has gone too.

The linking order is really some black magic which I'm not getting it. :(

**Comment by rk700** [comment] 2016-06-03 02:00
MuPDF comes with all the third party libraries because they are necessary. As a result, if you compile MuPDF from source, then the file `libmupdfthird.a` would contain all the symbols. For example, `hb_font_destroy` is a symbol needed by `libmupdf.a`:
```
nm build/release/libmupdf.a | grep hb_font_destroy
                 U hb_font_destroy
```
and you can find it in `libmupdfthird.a`:
```
$ nm build/release/libmupdfthird.a | grep hb_font_destroy
0000000000002700 T hb_font_destroy
```

However, some Linux distribution(at least Arch Linux) would remove the bundled libraries and use system libraries instead:
https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/mupdf#n34
As a result, `hb_font_destroy` is not contained in the system's `libmupdfthird.a`:
```
$ nm /usr/lib/libmupdfthird.a | grep hb_font_destroy
(Empty)
```
That's why I keep the third party libraries in `setup.py`.

It seems that some symbols from your system's `freetype` result in the crash. And by removing it, the symbols from `libmupdfthird.a` are used.

**Comment by rk700** [comment] 2016-06-03 02:03
But I think the symbols from `freetype` are used if it is in front of `mupdfthird`, which is really weird.

**Comment by mozbugbox** [comment] 2016-06-03 02:30
In that case, I guess the freetype shipped in thirdparty is not compatible with the system freetype (`libfreetype6` Debian testing), to which gtk+ was linked to.

Since most GUI toolkits links to system `freetype`, and which could be not compatible with the `freetype` included in the `mupdfthird`, I think the `freetype` need to be put in front of `mupdfthird`?

**Comment by rk700** [comment] 2016-06-04 01:39
Yep. But what makes me confused is that the issue can also be resolved by removing `freetype` from `setup.py`, in which case symbols from `mupdfthird` are used instead.

I've tested on Arch Linux and everything's fine if I put `mupdfthird` at the end of the list. So I think it's OK to make such a workaround though we still cannot figure out the reason. Please make sure that the new `setup.py` works on your machine and create a PR. Thanks!

**Comment by mozbugbox** [comment] 2016-06-04 04:21
The thing is that libmupdf.a is a static lib, it does not need to resolve external symbol. On the other hands, _fitz.so is a shared lib that the symbols are resolved (if possible) at link time.

If you `nm _fitz.so` on `_fitz.so` linked *without* `freetype`, you can see that `hb_*` are actually resolved from the static libmupdfthird.a.

If the `mupdfthird` is put after all the shared libs: `'jbig2dec', 'openjp2', 'jpeg', 'freetype'`, then the symbols in the shared lib will not be defined in _fitz.so as can be seen in `nm _fitz.so`. And will be resolved at runtime.

It seems that the real problem is to put `mupdfthird` in front of the shared libs. in which case the symbols in the mupdfthird are resolved at link time but the shared libs are also linked in to _fitz.so as
```
	linux-vdso.so.1 (0x00007fff30d3c000)
	libfreetype.so.6 => /usr/lib/x86_64-linux-gnu/libfreetype.so.6 (0x00007f3780fd4000)
	libcrypto.so.1.0.2 => /usr/lib/x86_64-linux-gnu/libcrypto.so.1.0.2 (0x00007f3780b71000)
	libjbig2dec.so.0 => /usr/lib/x86_64-linux-gnu/libjbig2dec.so.0 (0x00007f3780956000)
	libopenjp2.so.7 => /usr/lib/x86_64-linux-gnu/libopenjp2.so.7 (0x00007f378071f000)
	libjpeg.so.62 => /usr/lib/x86_64-linux-gnu/libjpeg.so.62 (0x00007f37804c6000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f37802a8000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f377ff04000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f377fce9000)
	libpng16.so.16 => /usr/lib/x86_64-linux-gnu/libpng16.so.16 (0x00007f377fab6000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f377f8b2000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f377f5b4000)
	/lib64/ld-linux-x86-64.so.2 (0x00005646c8121000)
```
That means we linked both statically and dynamically to the same libraries. Some bad thing happens somewhere.

Anyway, the libraries should really be one of the:
```
libraries = ["mupdf", "mupdfthird"]
```
or 
```
libraries = ["mupdf", 'freetype', "crypto", 'jbig2dec', 'openjp2', 'jpeg']
```

I guess if some system shared libs are missing, `'mupdfthird'` could be appended to the 2nd option.

**Comment by rk700** [comment] 2016-06-04 09:27
Actually `libmupdfthird.a` contains symbols for the `mujs` part. As a result, `libmupdfthird.a` is essential when building PyMuPDF. 

So I think the libraries should be set in the following way:
- If MuPDF is compiled from source with all the bundled third party libraries, then 
```
libraries = ["mupdf", "mupdfthird"]
```
would be enough, which is your case.

- If MuPDF is installed from the repo, or more exactly, it needs the third party libraries from system. Then
```
libraries = ["mupdf", 'mupdfthird', 'freetype', "crypto", 'jbig2dec', 'openjp2', 'jpeg']
```
And the order of the libraries can be changed, as long as `mupdf` is the first one.

**Comment by rk700** [comment] 2016-06-05 00:21
Issue closed as the PR https://github.com/rk700/PyMuPDF/pull/57 has been merged

**Closed by rk700** 2016-06-05 00:21 UTC
